configs:
  config_json:
    content: |
      {
      "USE_MODELSCOPE": "0",
      "translators": [
        {
            "name": "ollama",
            "envs": {
                "OLLAMA_HOST": "http://${OLLAMA_HOST:-127.0.0.1}:11434",
      "OLLAMA_MODEL": "${OLLAMA_MODEL:-aya-expanse:32b}"
            }
        }
      ]
      }
  prompt:
    content: |
      あなたはプロフェッショナルで正確な機械翻訳エンジンである。
      以下のmarkdownテキストを日本語に翻訳せよ。
      文体はすべて常態で統一し、敬体(ですます調)は使ってはならない。
      テキストに{v0}や{v1}などが含まれていた場合、これは数式のプレースホルダである。これらはそのまま出力せよ。存在しない場合は追加してはならない。
      翻訳結果のみを出力し、他のテキストは含めないこと。
      Source Text: $${text}
      Translated Text:

services:
    zotero-pdf2zh:
        build:
            context: .
            dockerfile: Dockerfile
        image: zotero-pdf2zh
        container_name: zotero-pdf2zh
        restart: unless-stopped
        ports:
            - 8888:8888
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - pdf2zh_translated:/app/translated
        configs:
          - source: config_json
            target: /app/config.json
          - source: prompt
            target: /app/prompt.txt
volumes:
    pdf2zh_translated:

